### ISSUE TITLE
cannot read the property set undefined

### ISSUE THREAD

**Issue by priya-vr** [pradeep1991singh/react-native-secure-key-store#3]
I am getting error "cannot read the property set undefined" . when calling 

    RNSecureKeyStore.set("key1", "value1")
	.then((res) => {
		console.log(res);
	}, (err) => {
		console.log(err);
	});
My RN version is
             "react-native": "0.46.4",
	     "react-native-secure-key-store": "^1.0.5",
But the issue still existing, after running:
react-native link
react-native run-ios.Please give any tips for solving problem

**Comment by JayzWalker** [comment]
it work out for me
- just downgrade RN version to 0.42.0
- npm install
- react-native link
- upgrade back to 0.46.4 or higher
- npm install 
- done

**Comment by priya-vr** [comment]
@JayzWalker :thanks for the replay, Actually  downgrade RN Version is not possible in my case ,becz it will affect my other frameworks.

**Comment by JayzWalker** [comment]
the reason of doing downgrade... is just to using react-native link working properly. coz I don't know why it doesn't work with v0.46. so after I link react-native-secure-key-store to both my iOS and android.. I immediately upgrade back to 0.46.. and it work...
one more thing... this morning I just get it work with RN v0.47 and react-native-secure-key-store 1.0.6

**Comment by pradeep1991singh** [comment]
RN v0.47 has removed unused method calls and as a result of that seems `react-native link` is not working properly. This issue can be fixed in two ways 

1. Set `"react-native-secure-key-store": "1.0.5"` in your `package.json`.
2. Or Link `"react-native-secure-key-store"` library using [manual installation](https://github.com/pradeep1991singh/react-native-secure-key-store/blob/master/README.md#manual-installation) not using [automtically installation](https://github.com/pradeep1991singh/react-native-secure-key-store/blob/master/README.md#mostly-automatic-installation)

**Comment by pradeep1991singh** [comment]
@priya-vr did you tried above steps? is the problem still exists?

**Comment by pradeep1991singh** [comment]
@priya-vr For now I am closing this issue because of inactivity, open it again if you like.

**Comment by priya-vr** [comment]
@pradeep1991singh :Sorry for the delay, I have tried all these steps ,again i am getting same error 
'cannot read the property set of undefined'

**Comment by gregorgr** [comment]
Problem persists:
"expo": "^49.0.2",
"react-native": "^0.72.3",
"react-native-secure-key-store": "^2.0.10",

when getting string key1

// For retrieving key
RNSecureKeyStore.get("key1")
	.then((res) => {
		console.log(res);
	}, (err) => {
		console.log(err);
	});
